# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import ProtocolBuffer_pb2 as ProtocolBuffer__pb2


class MessagesStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.conversar = channel.stream_stream(
        '/Messages/conversar',
        request_serializer=ProtocolBuffer__pb2.getComunicationRequest.SerializeToString,
        response_deserializer=ProtocolBuffer__pb2.getComunicationResponse.FromString,
        )
    self.editar = channel.stream_stream(
        '/Messages/editar',
        request_serializer=ProtocolBuffer__pb2.getEditTextRequest.SerializeToString,
        response_deserializer=ProtocolBuffer__pb2.getEditTextResponse.FromString,
        )
    self.eliminar = channel.stream_stream(
        '/Messages/eliminar',
        request_serializer=ProtocolBuffer__pb2.getDeletRequest.SerializeToString,
        response_deserializer=ProtocolBuffer__pb2.getDeletResponse.FromString,
        )


class MessagesServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def conversar(self, request_iterator, context):
    """Metodo que sirve para crear la conexion 
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def editar(self, request_iterator, context):
    """rpc reenviar (stream getC)
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def eliminar(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MessagesServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'conversar': grpc.stream_stream_rpc_method_handler(
          servicer.conversar,
          request_deserializer=ProtocolBuffer__pb2.getComunicationRequest.FromString,
          response_serializer=ProtocolBuffer__pb2.getComunicationResponse.SerializeToString,
      ),
      'editar': grpc.stream_stream_rpc_method_handler(
          servicer.editar,
          request_deserializer=ProtocolBuffer__pb2.getEditTextRequest.FromString,
          response_serializer=ProtocolBuffer__pb2.getEditTextResponse.SerializeToString,
      ),
      'eliminar': grpc.stream_stream_rpc_method_handler(
          servicer.eliminar,
          request_deserializer=ProtocolBuffer__pb2.getDeletRequest.FromString,
          response_serializer=ProtocolBuffer__pb2.getDeletResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Messages', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
