# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ProtocolBuffer.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ProtocolBuffer.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x14ProtocolBuffer.proto\"i\n\x16getComunicationRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0f\n\x05texto\x18\x02 \x01(\tH\x00\x12\x0f\n\x05\x61udio\x18\x03 \x01(\x0cH\x00\x12\x10\n\x06imagen\x18\x04 \x01(\x0cH\x00\x42\t\n\x07\x63ontent\"j\n\x17getComunicationResponse\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0f\n\x05texto\x18\x02 \x01(\tH\x00\x12\x0f\n\x05\x61udio\x18\x03 \x01(\x0cH\x00\x12\x10\n\x06imagen\x18\x04 \x01(\x0cH\x00\x42\t\n\x07\x63ontent\"#\n\x12getEditTextRequest\x12\r\n\x05texto\x18\x01 \x01(\t\"$\n\x13getEditTextResponse\x12\r\n\x05texto\x18\x01 \x01(\t\"P\n\x0fgetDeletRequest\x12\x0f\n\x05texto\x18\x02 \x01(\tH\x00\x12\x0f\n\x05\x61udio\x18\x03 \x01(\x0cH\x00\x12\x10\n\x06imagen\x18\x04 \x01(\x0cH\x00\x42\t\n\x07\x63ontent\"\x12\n\x10getDeletResponse2\xbc\x01\n\x08Messages\x12\x42\n\tconversar\x12\x17.getComunicationRequest\x1a\x18.getComunicationResponse(\x01\x30\x01\x12\x37\n\x06\x65\x64itar\x12\x13.getEditTextRequest\x1a\x14.getEditTextResponse(\x01\x30\x01\x12\x33\n\x08\x65liminar\x12\x10.getDeletRequest\x1a\x11.getDeletResponse(\x01\x30\x01\x62\x06proto3')
)




_GETCOMUNICATIONREQUEST = _descriptor.Descriptor(
  name='getComunicationRequest',
  full_name='getComunicationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='getComunicationRequest.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='texto', full_name='getComunicationRequest.texto', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='audio', full_name='getComunicationRequest.audio', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='imagen', full_name='getComunicationRequest.imagen', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='content', full_name='getComunicationRequest.content',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=24,
  serialized_end=129,
)


_GETCOMUNICATIONRESPONSE = _descriptor.Descriptor(
  name='getComunicationResponse',
  full_name='getComunicationResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='getComunicationResponse.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='texto', full_name='getComunicationResponse.texto', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='audio', full_name='getComunicationResponse.audio', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='imagen', full_name='getComunicationResponse.imagen', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='content', full_name='getComunicationResponse.content',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=131,
  serialized_end=237,
)


_GETEDITTEXTREQUEST = _descriptor.Descriptor(
  name='getEditTextRequest',
  full_name='getEditTextRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='texto', full_name='getEditTextRequest.texto', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=239,
  serialized_end=274,
)


_GETEDITTEXTRESPONSE = _descriptor.Descriptor(
  name='getEditTextResponse',
  full_name='getEditTextResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='texto', full_name='getEditTextResponse.texto', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=276,
  serialized_end=312,
)


_GETDELETREQUEST = _descriptor.Descriptor(
  name='getDeletRequest',
  full_name='getDeletRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='texto', full_name='getDeletRequest.texto', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='audio', full_name='getDeletRequest.audio', index=1,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='imagen', full_name='getDeletRequest.imagen', index=2,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='content', full_name='getDeletRequest.content',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=314,
  serialized_end=394,
)


_GETDELETRESPONSE = _descriptor.Descriptor(
  name='getDeletResponse',
  full_name='getDeletResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=396,
  serialized_end=414,
)

_GETCOMUNICATIONREQUEST.oneofs_by_name['content'].fields.append(
  _GETCOMUNICATIONREQUEST.fields_by_name['texto'])
_GETCOMUNICATIONREQUEST.fields_by_name['texto'].containing_oneof = _GETCOMUNICATIONREQUEST.oneofs_by_name['content']
_GETCOMUNICATIONREQUEST.oneofs_by_name['content'].fields.append(
  _GETCOMUNICATIONREQUEST.fields_by_name['audio'])
_GETCOMUNICATIONREQUEST.fields_by_name['audio'].containing_oneof = _GETCOMUNICATIONREQUEST.oneofs_by_name['content']
_GETCOMUNICATIONREQUEST.oneofs_by_name['content'].fields.append(
  _GETCOMUNICATIONREQUEST.fields_by_name['imagen'])
_GETCOMUNICATIONREQUEST.fields_by_name['imagen'].containing_oneof = _GETCOMUNICATIONREQUEST.oneofs_by_name['content']
_GETCOMUNICATIONRESPONSE.oneofs_by_name['content'].fields.append(
  _GETCOMUNICATIONRESPONSE.fields_by_name['texto'])
_GETCOMUNICATIONRESPONSE.fields_by_name['texto'].containing_oneof = _GETCOMUNICATIONRESPONSE.oneofs_by_name['content']
_GETCOMUNICATIONRESPONSE.oneofs_by_name['content'].fields.append(
  _GETCOMUNICATIONRESPONSE.fields_by_name['audio'])
_GETCOMUNICATIONRESPONSE.fields_by_name['audio'].containing_oneof = _GETCOMUNICATIONRESPONSE.oneofs_by_name['content']
_GETCOMUNICATIONRESPONSE.oneofs_by_name['content'].fields.append(
  _GETCOMUNICATIONRESPONSE.fields_by_name['imagen'])
_GETCOMUNICATIONRESPONSE.fields_by_name['imagen'].containing_oneof = _GETCOMUNICATIONRESPONSE.oneofs_by_name['content']
_GETDELETREQUEST.oneofs_by_name['content'].fields.append(
  _GETDELETREQUEST.fields_by_name['texto'])
_GETDELETREQUEST.fields_by_name['texto'].containing_oneof = _GETDELETREQUEST.oneofs_by_name['content']
_GETDELETREQUEST.oneofs_by_name['content'].fields.append(
  _GETDELETREQUEST.fields_by_name['audio'])
_GETDELETREQUEST.fields_by_name['audio'].containing_oneof = _GETDELETREQUEST.oneofs_by_name['content']
_GETDELETREQUEST.oneofs_by_name['content'].fields.append(
  _GETDELETREQUEST.fields_by_name['imagen'])
_GETDELETREQUEST.fields_by_name['imagen'].containing_oneof = _GETDELETREQUEST.oneofs_by_name['content']
DESCRIPTOR.message_types_by_name['getComunicationRequest'] = _GETCOMUNICATIONREQUEST
DESCRIPTOR.message_types_by_name['getComunicationResponse'] = _GETCOMUNICATIONRESPONSE
DESCRIPTOR.message_types_by_name['getEditTextRequest'] = _GETEDITTEXTREQUEST
DESCRIPTOR.message_types_by_name['getEditTextResponse'] = _GETEDITTEXTRESPONSE
DESCRIPTOR.message_types_by_name['getDeletRequest'] = _GETDELETREQUEST
DESCRIPTOR.message_types_by_name['getDeletResponse'] = _GETDELETRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

getComunicationRequest = _reflection.GeneratedProtocolMessageType('getComunicationRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETCOMUNICATIONREQUEST,
  '__module__' : 'ProtocolBuffer_pb2'
  # @@protoc_insertion_point(class_scope:getComunicationRequest)
  })
_sym_db.RegisterMessage(getComunicationRequest)

getComunicationResponse = _reflection.GeneratedProtocolMessageType('getComunicationResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETCOMUNICATIONRESPONSE,
  '__module__' : 'ProtocolBuffer_pb2'
  # @@protoc_insertion_point(class_scope:getComunicationResponse)
  })
_sym_db.RegisterMessage(getComunicationResponse)

getEditTextRequest = _reflection.GeneratedProtocolMessageType('getEditTextRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETEDITTEXTREQUEST,
  '__module__' : 'ProtocolBuffer_pb2'
  # @@protoc_insertion_point(class_scope:getEditTextRequest)
  })
_sym_db.RegisterMessage(getEditTextRequest)

getEditTextResponse = _reflection.GeneratedProtocolMessageType('getEditTextResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETEDITTEXTRESPONSE,
  '__module__' : 'ProtocolBuffer_pb2'
  # @@protoc_insertion_point(class_scope:getEditTextResponse)
  })
_sym_db.RegisterMessage(getEditTextResponse)

getDeletRequest = _reflection.GeneratedProtocolMessageType('getDeletRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETDELETREQUEST,
  '__module__' : 'ProtocolBuffer_pb2'
  # @@protoc_insertion_point(class_scope:getDeletRequest)
  })
_sym_db.RegisterMessage(getDeletRequest)

getDeletResponse = _reflection.GeneratedProtocolMessageType('getDeletResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETDELETRESPONSE,
  '__module__' : 'ProtocolBuffer_pb2'
  # @@protoc_insertion_point(class_scope:getDeletResponse)
  })
_sym_db.RegisterMessage(getDeletResponse)



_MESSAGES = _descriptor.ServiceDescriptor(
  name='Messages',
  full_name='Messages',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=417,
  serialized_end=605,
  methods=[
  _descriptor.MethodDescriptor(
    name='conversar',
    full_name='Messages.conversar',
    index=0,
    containing_service=None,
    input_type=_GETCOMUNICATIONREQUEST,
    output_type=_GETCOMUNICATIONRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='editar',
    full_name='Messages.editar',
    index=1,
    containing_service=None,
    input_type=_GETEDITTEXTREQUEST,
    output_type=_GETEDITTEXTRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='eliminar',
    full_name='Messages.eliminar',
    index=2,
    containing_service=None,
    input_type=_GETDELETREQUEST,
    output_type=_GETDELETRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MESSAGES)

DESCRIPTOR.services_by_name['Messages'] = _MESSAGES

# @@protoc_insertion_point(module_scope)
